sudo: required

language: cpp

addons:
  ssh_known_hosts: developers.golos.io
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

before_install:
  - sudo apt-get install python-software-properties 
  - sudo apt-add-repository -y ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update
  - sudo apt-get install -y doxygen 
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script:
  - bash deploy/deploy.sh


